version: '3.4'


services:

 sourcingsqldb:
    image: mcr.microsoft.com/mssql/server
 
 surveyapi:
    image: ${DOCKER_REGISTRY-}surveyapi
    build:
      context: .
      dockerfile: SurveyApi/Dockerfile
